name: Docker Image CI

on:
  pull_request
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t shell .
    - name: Prepare System tests
      run: docker build -t comp0010-system-test .
    - name: Run System tests
      run: python system_test/tests.py -v
    - name: Generate Documentation
      run: echo "Under construction!!!"
